"""Repository for dq_recommendations -- actionable fixes generated by dqBot."""

import json
import logging

from backend.db.connection import get_conn

logger = logging.getLogger(__name__)

_VALID_STATUSES = frozenset({"approved", "rejected", "snoozed", "superseded", "dismissed"})


def create_recommendation(
    user_id: int,
    run_id: int,
    observation_id: int,
    action_type: str,
    headline: str,
    rationale: str,
    self_classification: str,
    rank_in_run: int,
    affected_entity_type: str,
    affected_entity_ids: list[str],
    outlier_signals: dict | None = None,
    action_payload: dict | None = None,
) -> dict:
    """Insert a recommendation into dq_recommendations.

    affected_entity_ids, outlier_signals, and action_payload are marshaled to
    JSONB via json.dumps. action_payload (migration 042) carries the
    machine-actionable instructions for the approve-applies path (spec S4);
    None for action_types that stay record-only, or when a pre-detector /
    the LLM pass couldn't derive one.
    Returns the inserted row as dict.
    """
    with get_conn() as conn, conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO dq_recommendations
                (user_id, run_id, observation_id, action_type, headline, rationale,
                 self_classification, rank_in_run, affected_entity_type, affected_entity_ids,
                 outlier_signals, action_payload)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id, user_id, run_id, observation_id, action_type, headline,
                      rationale, self_classification, rank_in_run, affected_entity_type,
                      affected_entity_ids, status, user_note, reviewed_at,
                      superseded_by, created_at, promoted_at, outlier_signals,
                      action_payload, applied_at, applied_detail
            """,
            (
                user_id,
                run_id,
                observation_id,
                action_type,
                headline,
                rationale,
                self_classification,
                rank_in_run,
                affected_entity_type,
                json.dumps(affected_entity_ids),
                json.dumps(outlier_signals) if outlier_signals is not None else None,
                json.dumps(action_payload) if action_payload is not None else None,
            ),
        )
        r = cur.fetchone()

    return {
        "id": r[0],
        "user_id": r[1],
        "run_id": r[2],
        "observation_id": r[3],
        "action_type": r[4],
        "headline": r[5],
        "rationale": r[6],
        "self_classification": r[7],
        "rank_in_run": r[8],
        "affected_entity_type": r[9],
        "affected_entity_ids": r[10],
        "status": r[11],
        "user_note": r[12],
        "reviewed_at": r[13],
        "superseded_by": r[14],
        "created_at": r[15],
        "promoted_at": r[16],
        "outlier_signals": r[17],
        "action_payload": r[18],
        "applied_at": r[19],
        "applied_detail": r[20],
    }


def list_for_observation(user_id: int, observation_id: int) -> list[dict]:
    """List all recommendations linked to one observation (any status).

    Used by the Receipt pane to render Layer 4 (Alternatives) -- sibling
    recommendations for the same finding, including superseded ones so the
    user can see the full history.
    """
    with get_conn() as conn, conn.cursor() as cur:
        cur.execute(
            """
            SELECT id, user_id, run_id, observation_id, action_type, headline,
                   rationale, self_classification, rank_in_run,
                   affected_entity_type, affected_entity_ids, status, user_note,
                   reviewed_at, superseded_by, created_at, promoted_at,
                   outlier_signals, action_payload, applied_at, applied_detail
            FROM dq_recommendations
            WHERE user_id = %s AND observation_id = %s
            ORDER BY created_at DESC
            """,
            (user_id, observation_id),
        )
        rows = cur.fetchall()
    return [
        {
            "id": r[0],
            "user_id": r[1],
            "run_id": r[2],
            "observation_id": r[3],
            "action_type": r[4],
            "headline": r[5],
            "rationale": r[6],
            "self_classification": r[7],
            "rank_in_run": r[8],
            "affected_entity_type": r[9],
            "affected_entity_ids": r[10],
            "status": r[11],
            "user_note": r[12],
            "reviewed_at": r[13].isoformat() if r[13] else None,
            "superseded_by": r[14],
            "created_at": r[15].isoformat() if r[15] else None,
            "promoted_at": r[16].isoformat() if r[16] else None,
            "outlier_signals": r[17],
            "action_payload": r[18],
            "applied_at": r[19].isoformat() if r[19] else None,
            "applied_detail": r[20],
        }
        for r in rows
    ]


def list_pending(
    user_id: int,
    limit: int = 5,
    include_superseded: bool = False,
) -> list[dict]:
    """List recommendations for a user, ordered by promoted_at then rank_in_run.

    Promoted recs surface first (promoted_at DESC NULLS LAST), then un-promoted
    recs in rank order. This means a promoted rank-8 rec will appear before an
    un-promoted rank-1 rec in the result set.

    By default returns only status='pending' rows. When include_superseded=True,
    also returns status='superseded' rows so the all-findings expander can render
    the supersession chain (greyed cards with "replaced by ->" links).
    """
    statuses: list[str] = ["pending"]
    if include_superseded:
        statuses.append("superseded")
    with get_conn() as conn, conn.cursor() as cur:
        cur.execute(
            """
            SELECT id, user_id, run_id, observation_id, action_type, headline,
                   rationale, self_classification, rank_in_run, affected_entity_type,
                   affected_entity_ids, status, user_note, reviewed_at,
                   superseded_by, created_at, promoted_at, outlier_signals,
                   action_payload, applied_at, applied_detail
            FROM dq_recommendations
            WHERE user_id = %s AND status = ANY(%s)
            ORDER BY promoted_at DESC NULLS LAST, rank_in_run ASC
            LIMIT %s
            """,
            (user_id, statuses, limit),
        )
        return [
            {
                "id": r[0],
                "user_id": r[1],
                "run_id": r[2],
                "observation_id": r[3],
                "action_type": r[4],
                "headline": r[5],
                "rationale": r[6],
                "self_classification": r[7],
                "rank_in_run": r[8],
                "affected_entity_type": r[9],
                "affected_entity_ids": r[10],
                "status": r[11],
                "user_note": r[12],
                "reviewed_at": r[13],
                "superseded_by": r[14],
                "created_at": r[15],
                "promoted_at": r[16],
                "outlier_signals": r[17],
                "action_payload": r[18],
                "applied_at": r[19],
                "applied_detail": r[20],
            }
            for r in cur.fetchall()
        ]


def list_all_for_run(run_id: int) -> list[dict]:
    """List all recommendations for a run, ordered by rank_in_run.

    Includes all statuses (pending, approved, rejected, etc.).
    """
    with get_conn() as conn, conn.cursor() as cur:
        cur.execute(
            """
            SELECT id, user_id, run_id, observation_id, action_type, headline,
                   rationale, self_classification, rank_in_run, affected_entity_type,
                   affected_entity_ids, status, user_note, reviewed_at,
                   superseded_by, created_at, promoted_at, outlier_signals,
                   action_payload, applied_at, applied_detail
            FROM dq_recommendations
            WHERE run_id = %s
            ORDER BY rank_in_run ASC
            """,
            (run_id,),
        )
        return [
            {
                "id": r[0],
                "user_id": r[1],
                "run_id": r[2],
                "observation_id": r[3],
                "action_type": r[4],
                "headline": r[5],
                "rationale": r[6],
                "self_classification": r[7],
                "rank_in_run": r[8],
                "affected_entity_type": r[9],
                "affected_entity_ids": r[10],
                "status": r[11],
                "user_note": r[12],
                "reviewed_at": r[13],
                "superseded_by": r[14],
                "created_at": r[15],
                "promoted_at": r[16],
                "outlier_signals": r[17],
                "action_payload": r[18],
                "applied_at": r[19],
                "applied_detail": r[20],
            }
            for r in cur.fetchall()
        ]


def update_status(
    rec_id: int,
    new_status: str,
    user_note: str | None = None,
) -> dict | None:
    """Update the status of a recommendation.

    Validates new_status is in _VALID_STATUSES before executing.
    Sets reviewed_at = NOW().
    Returns the updated row as dict.
    """
    if new_status not in _VALID_STATUSES:
        raise ValueError(f"invalid status: {new_status}")

    with get_conn() as conn, conn.cursor() as cur:
        cur.execute(
            """
            UPDATE dq_recommendations
            SET status = %s, reviewed_at = NOW(), user_note = %s
            WHERE id = %s
            RETURNING id, user_id, run_id, observation_id, action_type, headline,
                      rationale, self_classification, rank_in_run, affected_entity_type,
                      affected_entity_ids, status, user_note, reviewed_at,
                      superseded_by, created_at, promoted_at, outlier_signals,
                      action_payload, applied_at, applied_detail
            """,
            (new_status, user_note, rec_id),
        )
        r = cur.fetchone()

    if r is None:
        return None
    return {
        "id": r[0],
        "user_id": r[1],
        "run_id": r[2],
        "observation_id": r[3],
        "action_type": r[4],
        "headline": r[5],
        "rationale": r[6],
        "self_classification": r[7],
        "rank_in_run": r[8],
        "affected_entity_type": r[9],
        "affected_entity_ids": r[10],
        "status": r[11],
        "user_note": r[12],
        "reviewed_at": r[13],
        "superseded_by": r[14],
        "created_at": r[15],
        "promoted_at": r[16],
        "outlier_signals": r[17],
        "action_payload": r[18],
        "applied_at": r[19],
        "applied_detail": r[20],
    }


def mark_applied(rec_id: int, detail: dict) -> dict | None:
    """Record what the approve-applies path (spec S5) actually did.

    Sets applied_at = NOW() and applied_detail = detail (JSONB). Called
    regardless of whether the apply succeeded -- detail carries either the
    applied action's summary or {"error": ...} / a record-only explanation;
    status still flips to approved via update_status separately (the verdict
    stands even when the apply needs a retry). Returns the updated row, or
    None if rec_id doesn't exist.
    """
    with get_conn() as conn, conn.cursor() as cur:
        cur.execute(
            """
            UPDATE dq_recommendations
            SET applied_at = NOW(), applied_detail = %s
            WHERE id = %s
            RETURNING id, user_id, run_id, observation_id, action_type, headline,
                      rationale, self_classification, rank_in_run, affected_entity_type,
                      affected_entity_ids, status, user_note, reviewed_at,
                      superseded_by, created_at, promoted_at, outlier_signals,
                      action_payload, applied_at, applied_detail
            """,
            (json.dumps(detail), rec_id),
        )
        r = cur.fetchone()

    if r is None:
        return None
    return {
        "id": r[0],
        "user_id": r[1],
        "run_id": r[2],
        "observation_id": r[3],
        "action_type": r[4],
        "headline": r[5],
        "rationale": r[6],
        "self_classification": r[7],
        "rank_in_run": r[8],
        "affected_entity_type": r[9],
        "affected_entity_ids": r[10],
        "status": r[11],
        "user_note": r[12],
        "reviewed_at": r[13],
        "superseded_by": r[14],
        "created_at": r[15],
        "promoted_at": r[16],
        "outlier_signals": r[17],
        "action_payload": r[18],
        "applied_at": r[19],
        "applied_detail": r[20],
    }


def resolve_stale_cluster_recs(user_id: int, live_stable_ids: list[str]) -> int:
    """Auto-expire pending cluster-entity recs whose target dissolved in a
    recluster (spec S3): dismiss any pending recommendation linked to a
    cluster-entity observation whose entity_id (a stable_id) is not in
    live_stable_ids, the carried set from the new generation.

    Guard: an empty live_stable_ids means identity carry-forward was off or
    broken this run, NOT that every cluster dissolved -- in that case this
    is a no-op (returns 0) rather than mass-dismissing the queue.

    Returns the number of recommendations dismissed.
    """
    if not live_stable_ids:
        return 0

    with get_conn() as conn, conn.cursor() as cur:
        cur.execute(
            """
            UPDATE dq_recommendations r
            SET status = 'dismissed',
                reviewed_at = NOW(),
                user_note = '[auto] target cluster dissolved in recluster (stable_id no longer carried)'
            WHERE r.user_id = %s
              AND r.status = 'pending'
              AND r.affected_entity_type = 'cluster'
              AND EXISTS (
                  SELECT 1 FROM dq_observations o
                  WHERE o.id = r.observation_id
                    AND o.entity_type = 'cluster'
                    AND o.entity_id != ALL(%s)
              )
            """,
            (user_id, live_stable_ids),
        )
        return cur.rowcount


def supersede(old_rec_id: int, new_payload: dict) -> dict:
    """Supersede an old recommendation with a new one.

    Atomically:
      1. INSERT the new recommendation from new_payload
      2. UPDATE old rec: status='superseded', superseded_by=<new_id>

    new_payload may include an optional "action_payload" key (migration 042);
    absent/None is stored as NULL, same as create_recommendation.

    Returns the NEW recommendation as dict.
    """
    with get_conn() as conn, conn.cursor() as cur:
        # Insert the new recommendation
        cur.execute(
            """
            INSERT INTO dq_recommendations
                (user_id, run_id, observation_id, action_type, headline, rationale,
                 self_classification, rank_in_run, affected_entity_type, affected_entity_ids,
                 outlier_signals, action_payload)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id, user_id, run_id, observation_id, action_type, headline,
                      rationale, self_classification, rank_in_run, affected_entity_type,
                      affected_entity_ids, status, user_note, reviewed_at,
                      superseded_by, created_at, promoted_at, outlier_signals,
                      action_payload, applied_at, applied_detail
            """,
            (
                new_payload["user_id"],
                new_payload["run_id"],
                new_payload["observation_id"],
                new_payload["action_type"],
                new_payload["headline"],
                new_payload["rationale"],
                new_payload["self_classification"],
                new_payload["rank_in_run"],
                new_payload["affected_entity_type"],
                json.dumps(new_payload["affected_entity_ids"]),
                json.dumps(new_payload["outlier_signals"]) if new_payload.get("outlier_signals") is not None else None,
                json.dumps(new_payload["action_payload"]) if new_payload.get("action_payload") is not None else None,
            ),
        )
        new_row = cur.fetchone()
        new_id = new_row[0]

        # Mark the old recommendation as superseded
        cur.execute(
            """
            UPDATE dq_recommendations
            SET status = 'superseded', superseded_by = %s
            WHERE id = %s
            """,
            (new_id, old_rec_id),
        )

    return {
        "id": new_row[0],
        "user_id": new_row[1],
        "run_id": new_row[2],
        "observation_id": new_row[3],
        "action_type": new_row[4],
        "headline": new_row[5],
        "rationale": new_row[6],
        "self_classification": new_row[7],
        "rank_in_run": new_row[8],
        "affected_entity_type": new_row[9],
        "affected_entity_ids": new_row[10],
        "status": new_row[11],
        "user_note": new_row[12],
        "reviewed_at": new_row[13],
        "superseded_by": new_row[14],
        "created_at": new_row[15],
        "promoted_at": new_row[16],
        "outlier_signals": new_row[17],
        "action_payload": new_row[18],
        "applied_at": new_row[19],
        "applied_detail": new_row[20],
    }


def promote(rec_id: int, user_id: int) -> dict | None:
    """Set promoted_at = NOW() on a user's rec. Returns the updated row or None if not found."""
    with get_conn() as conn, conn.cursor() as cur:
        cur.execute(
            """
            UPDATE dq_recommendations
            SET promoted_at = NOW()
            WHERE id = %s AND user_id = %s
            RETURNING id, user_id, run_id, observation_id, action_type, headline,
                      rationale, self_classification, rank_in_run, affected_entity_type,
                      affected_entity_ids, status, user_note, reviewed_at,
                      superseded_by, created_at, promoted_at, outlier_signals
            """,
            (rec_id, user_id),
        )
        r = cur.fetchone()

    if r is None:
        return None
    return {
        "id": r[0],
        "user_id": r[1],
        "run_id": r[2],
        "observation_id": r[3],
        "action_type": r[4],
        "headline": r[5],
        "rationale": r[6],
        "self_classification": r[7],
        "rank_in_run": r[8],
        "affected_entity_type": r[9],
        "affected_entity_ids": r[10],
        "status": r[11],
        "user_note": r[12],
        "reviewed_at": r[13],
        "superseded_by": r[14],
        "created_at": r[15],
        "promoted_at": r[16],
        "outlier_signals": r[17],
    }


def calibration_by_action_type(user_id: int, limit: int = 20) -> list[dict]:
    """Approval-rate rollup over the user's last-N recs, grouped by action_type.

    Only counts recs that have been reviewed (approved OR rejected). Snoozed,
    superseded, and dismissed are excluded because they're neither accept
    nor reject signals.

    Returns a list of dicts, one per action_type seen in the window:
      {
        "action_type": str,
        "approved": int,
        "rejected": int,
        "total_reviewed": int,
        "approval_rate": float,  # approved / total_reviewed, 0.0 if 0
      }
    Sorted by total_reviewed DESC so the most-reviewed types come first.
    """
    with get_conn() as conn, conn.cursor() as cur:
        cur.execute(
            """
            SELECT id, action_type, status
            FROM dq_recommendations
            WHERE user_id = %s AND status IN ('approved', 'rejected')
            ORDER BY reviewed_at DESC
            LIMIT %s
            """,
            (user_id, limit),
        )
        rows = cur.fetchall()

    # Aggregate in Python by action_type
    counts: dict[str, dict] = {}
    for _id, action_type, status in rows:
        if action_type not in counts:
            counts[action_type] = {"approved": 0, "rejected": 0}
        counts[action_type][status] += 1

    result = []
    for action_type, c in counts.items():
        approved = c["approved"]
        rejected = c["rejected"]
        total_reviewed = approved + rejected
        approval_rate = approved / total_reviewed if total_reviewed > 0 else 0.0
        result.append(
            {
                "action_type": action_type,
                "approved": approved,
                "rejected": rejected,
                "total_reviewed": total_reviewed,
                "approval_rate": approval_rate,
            }
        )

    result.sort(key=lambda x: x["total_reviewed"], reverse=True)
    return result


def calibration_summary(user_id: int) -> dict:
    """Get calibration summary (approval rate, etc.) for a user.

    Counts recommendations by status over the user's history.
    Computes approval_rate = approved / (approved + rejected), with guard for zero.

    Returns dict with: approved, rejected, superseded, snoozed, dismissed, total, approval_rate
    """
    with get_conn() as conn, conn.cursor() as cur:
        cur.execute(
            """
            SELECT
                COUNT(*) FILTER (WHERE status = 'approved') AS approved,
                COUNT(*) FILTER (WHERE status = 'rejected') AS rejected,
                COUNT(*) FILTER (WHERE status = 'superseded') AS superseded,
                COUNT(*) FILTER (WHERE status = 'snoozed') AS snoozed,
                COUNT(*) FILTER (WHERE status = 'dismissed') AS dismissed,
                COUNT(*) AS total
            FROM dq_recommendations
            WHERE user_id = %s
            """,
            (user_id,),
        )
        r = cur.fetchone()

    approved = r[0]
    rejected = r[1]
    superseded = r[2]
    snoozed = r[3]
    dismissed = r[4]
    total = r[5]

    # Compute approval_rate with guard for zero-denominator
    reviewed_count = approved + rejected
    approval_rate = approved / reviewed_count if reviewed_count > 0 else 0.0

    return {
        "approved": approved,
        "rejected": rejected,
        "superseded": superseded,
        "snoozed": snoozed,
        "dismissed": dismissed,
        "total": total,
        "approval_rate": approval_rate,
    }
