export declare const RANGE_DAYS: Record<string, number>;
export declare const GRANULARITY: Record<string, [string, string]>;
export declare const HOUR: number;
export declare const DAY: number;
export function normalizeRange(range: string | null | undefined): string;
export function isValidTz(tz: unknown): boolean;
export function wallOf(ms: number, tz: string): number;
export function isoWithOffset(wall: number, tz: string): string;
export function floorWall(wall: number, granularity: string): number;
export function stepWall(wall: number, granularity: string): number;
export function bucketWalls(firstMs: number, nowMs: number, tz: string, granularity: string): number[];
