"""ar5iv HTML parser + extraction quality gate.

Pure functions that turn ar5iv-rendered LaTeX HTML into structured sections
plus quality-gate metadata. No I/O — caller owns the HTTP fetch.

ar5iv (https://ar5iv.labs.arxiv.org) renders arXiv preprints from their
original LaTeX source via LaTeXML. Output is HTML5 with class-tagged
elements that mirror the LaTeX structure: ``ltx_section``, ``ltx_para``,
``ltx_ERROR``, ``ltx_title``, etc. Degraded renders return HTTP 200 with
inline ``ltx_ERROR`` markers — the post-fetch quality gate
(``arxiv_quality_gate``) inspects ``ParsedPaper.error_count`` to decide
whether to fall through to the PDF fallback path.

The shared types ``Section`` and ``ParsedPaper`` also live here because
the PDF parser (``arxiv_pdf_parser.parse_pdf``) emits the same shape so
the gate can run uniformly over either source.
"""

from dataclasses import dataclass, field
from typing import List, Literal, Optional

from bs4 import BeautifulSoup, Tag
from pydantic import BaseModel


# Errors-per-1K-chars above which a render is considered too degraded to
# accept. Placeholder; calibrated against the validation set in Phase 3
# (see docs/llm/arxiv-extraction-calibration.md once that lands).
DEFAULT_ERROR_DENSITY_THRESHOLD = 5.0


# LaTeXML container classes for section-like elements, mapped to their
# LaTeX hierarchy level. Used to identify which <section> nodes carry
# real content vs scaffolding.
_SECTION_LEVELS: dict[str, int] = {
    "ltx_section": 1,
    "ltx_subsection": 2,
    "ltx_subsubsection": 3,
    "ltx_paragraph": 4,
    "ltx_subparagraph": 5,
}

# Page chrome added by LaTeXML / ar5iv around the paper body. Removed
# before the section walk so footer "Generated by LaTeXML" content and
# ar5iv navigation don't leak into body_text.
_CHROME_SELECTORS: tuple[str, ...] = (
    "div.ltx_page_header",
    "div.ltx_page_footer",
    "footer",
    "nav",
)


class Section(BaseModel):
    """One section of a parsed paper.

    Flat list, not nested — ``level`` captures the LaTeX hierarchy
    (1=section, 2=subsection, ...). Persisted as part of ``ArxivPaper``
    so it must round-trip through Pydantic JSONB serialization.
    """

    name: str
    level: int
    text: str


@dataclass
class ParsedPaper:
    """Output of ``parse_ar5iv``. Transient — not persisted directly.

    Caller maps ``sections`` and ``body_text`` onto the persisted
    ``ArxivPaper`` and reads ``error_count`` / ``error_locations`` for
    the Phase 2 quality gate.
    """

    sections: List[Section]
    body_text: str
    error_count: int
    error_locations: List[str] = field(default_factory=list)


def parse_ar5iv(html: str) -> ParsedPaper:
    """Parse an ar5iv HTML render into structured sections.

    Returns an empty ``ParsedPaper`` when ``html`` is empty or contains
    no parseable sections — caller decides whether that triggers the
    PDF fallback.
    """
    if not html:
        return ParsedPaper(sections=[], body_text="", error_count=0)

    soup = BeautifulSoup(html, "lxml")

    for selector in _CHROME_SELECTORS:
        for node in soup.select(selector):
            node.decompose()

    sections: List[Section] = []
    for node in soup.find_all("section"):
        if not isinstance(node, Tag):
            continue
        level = _section_level(node)
        if level is None:
            continue
        text = _section_text(node)
        if not text.strip():
            continue
        sections.append(Section(name=_section_name(node), level=level, text=text))

    body_text = "\n\n".join(s.text for s in sections)

    error_nodes = soup.find_all(class_="ltx_ERROR")
    error_count = len(error_nodes)
    error_locations = [_error_context(n) for n in error_nodes]

    return ParsedPaper(
        sections=sections,
        body_text=body_text,
        error_count=error_count,
        error_locations=error_locations,
    )


def arxiv_quality_gate(
    parsed: ParsedPaper,
    *,
    error_density_threshold: float = DEFAULT_ERROR_DENSITY_THRESHOLD,
) -> Literal["accept", "fall_through"]:
    """Decide whether a parsed extraction is good enough to keep.

    Falls through (signaling the caller to try the PDF fallback) when:
      - No sections were parsed at all (extraction produced nothing
        usable; the source rendered to chrome-only or failed silently).
      - Error density exceeds the threshold (errors per 1000 chars of
        body text). Above this, a meaningful fraction of the body is
        garbled markers rather than prose, hurting RAG retrieval.

    Otherwise accepts the extraction. Operates uniformly over both
    ar5iv-parsed and PDF-parsed inputs since both produce ParsedPaper.

    The threshold is tunable for callers running calibration sweeps; in
    production it always uses the calibrated default.
    """
    if not parsed.sections:
        return "fall_through"
    text_chars = len(parsed.body_text)
    error_density = parsed.error_count / max(1.0, text_chars / 1000)
    if error_density > error_density_threshold:
        return "fall_through"
    return "accept"


def _section_level(node: Tag) -> Optional[int]:
    classes = node.get("class") or []
    for cls in classes:
        if cls in _SECTION_LEVELS:
            return _SECTION_LEVELS[cls]
    return None


def _section_name(node: Tag) -> str:
    title = node.find(class_="ltx_title")
    if title:
        return _normalize_whitespace(title.get_text(" ", strip=True))
    for level in range(1, 7):
        h = node.find(f"h{level}")
        if h:
            return _normalize_whitespace(h.get_text(" ", strip=True))
    return ""


def _section_text(node: Tag) -> str:
    """Concatenate paragraph text for a section, skipping nested subsections.

    Paragraphs whose nearest ``<section>`` ancestor is a child of ``node``
    belong to that nested section — they get their own flat ``Section``
    entry, so we exclude them here to avoid duplicating the same prose
    across parent and child sections.
    """
    parts: List[str] = []
    for para in node.find_all(class_="ltx_para", recursive=True):
        if para.find_parent("section") is not node:
            continue
        text = para.get_text(" ", strip=True)
        if text:
            parts.append(_normalize_whitespace(text))
    return "\n\n".join(parts)


def _error_context(node: Tag) -> str:
    parent_section = node.find_parent("section")
    if parent_section is not None:
        section_name = _section_name(parent_section)
        if section_name:
            return f"section: {section_name}"
    return "(unknown location)"


def _normalize_whitespace(text: str) -> str:
    return " ".join(text.split())
